/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenix2;
import Conexion_Base_de_Datos.conexionMySQL;
import java.awt.Image;
import java.awt.Toolkit;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author -Ing-Geraldo Andres
 */
public class ConfiCuenta extends javax.swing.JFrame {
int nAction;
String r1,ac1;
conexionMySQL cc=new conexionMySQL();
                Connection cn=cc.Conectar();
    /**
     * Creates new form FFFF
     */
    public ConfiCuenta() {
        this.setUndecorated(true);
        initComponents();
        i();
        inhabilitar();
          this.setLocationRelativeTo(null);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
     private static final char[] CONSTS_HEX = { '0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f' }; 
     public static String encriptaEnMD5(String stringAEncriptar)  
     {        
         try        {     
             MessageDigest msgd = MessageDigest.getInstance("MD5");      
             byte[] bytes = msgd.digest(stringAEncriptar.getBytes());     
             StringBuilder strbCadenaMD5 = new StringBuilder(2 * bytes.length); 
             for (int i = 0; i < bytes.length; i++)    
             {            
                 int bajo = (int)(bytes[i] & 0x0f);  
             int alto = (int)((bytes[i] & 0xf0) >> 4);    
             strbCadenaMD5.append(CONSTS_HEX[alto]);      
             strbCadenaMD5.append(CONSTS_HEX[bajo]);           }  
             return strbCadenaMD5.toString();      
         } catch (NoSuchAlgorithmException e) {         
             return null;        }  
     }     
    void i(){
    Image icon;
    icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Iconos/ful3.png"));
   
            
            
    setIconImage(icon);
    setVisible(true);
  }
     void habilitar(){
   txtn.setEnabled(true);
    txta.setEnabled(true);
    jButguardar.setEnabled(true);
    jPasswordField1.setEnabled(true);
    jTextUsuario.setEnabled(true);
    jButton2.setEnabled(true);
   jButton1.setEnabled(true);
    }
    
    void inhabilitar(){
    txtn.setEnabled(false);
    txta.setEnabled(false);
 
    jButguardar.setEnabled(false);
    jPasswordField1.setEnabled(false);
    jTextUsuario.setEnabled(false);
   jButton2.setEnabled(false);
   jButton1.setEnabled(false);
    }
    
    void limpiar(){
         txtn.setText("");
    txta.setText("");
   idf.setText("");
   jPasswordField1.setText("");
   jTextUsuario.setText("");
   
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lbcontraseña = new javax.swing.JLabel();
        idf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        jButguardar = new javax.swing.JButton();
        jBuCancelar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTION DE CUENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jTextUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextUsuario);
        jTextUsuario.setBounds(190, 60, 181, 29);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(190, 120, 181, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(48, 310, 0, 0);

        lbcontraseña.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbcontraseña);
        lbcontraseña.setBounds(48, 328, 0, 0);

        idf.setBackground(new java.awt.Color(102, 204, 255));
        idf.setForeground(new java.awt.Color(102, 204, 255));
        idf.setBorder(null);
        jPanel1.add(idf);
        idf.setBounds(16, 16, 0, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 40, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 100, 80, 17);

        txta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txta);
        txta.setBounds(190, 240, 181, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 160, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Apellido");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 220, 60, 17);

        txtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(txtn);
        txtn.setBounds(190, 180, 181, 28);

        jButguardar.setBackground(new java.awt.Color(0, 0, 0));
        jButguardar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButguardar.setForeground(new java.awt.Color(255, 255, 255));
        jButguardar.setText("GUARDAR");
        jButguardar.setBorder(null);
        jButguardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButguardar);
        jButguardar.setBounds(20, 100, 130, 51);

        jBuCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBuCancelar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jBuCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBuCancelar.setText("NUEVO");
        jBuCancelar.setBorder(null);
        jBuCancelar.setBorderPainted(false);
        jBuCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBuCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBuCancelar);
        jBuCancelar.setBounds(20, 40, 130, 51);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 160, 130, 51);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ELIMINAR");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 220, 130, 51);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("INICIO #");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 280, 90, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton4.setText("SALIR-->");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(270, 280, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {

           
            

            String ci,SQL,dd,id;

            limpiar();
            ci=JOptionPane.showInputDialog("Usuario a Eliminar");
            dd=JOptionPane.showInputDialog("Contraseña a Eliminar");

            SQL = " SELECT * FROM usuario WHERE usuario= '"+encriptaEnMD5(ci)+"' AND  contraseña='"+encriptaEnMD5(dd)+"'";

            Statement st = null;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);

            rs.next();
            id=(rs.getString("id$usu"));
            jTextUsuario.setText(ci);
            jPasswordField1.setText(dd);
             txtn.setText(rs.getString("nombre"));
             txta.setText(rs.getString("apellido"));
             r1=(rs.getString("rol"));
             ac1=(rs.getString("activo"));

            int resp= JOptionPane.showConfirmDialog(this, "Deseas Eliminarlo","Eliminar Dato",JOptionPane.YES_NO_OPTION);

            if(resp==JOptionPane.YES_NO_OPTION){
                try{
                    PreparedStatement psd=null;
                    SQL =" DELETE FROM usuario WHERE id$usu= '"+id+"'  ";
                    psd=cn.prepareStatement(SQL);
                    psd.execute();
                    psd.close();
                    JOptionPane.showMessageDialog(null,"Eliminado");
                }
                catch(SQLException ex){
                    JOptionPane.showMessageDialog(null,"Error");
                }

            }
            limpiar();
            inhabilitar();
        }
        catch (SQLException ex)
        {

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        habilitar();
        limpiar();

       
        String cod, SQL,c;

        this.nAction = 2;

        cod = JOptionPane.showInputDialog("Ingrese su Usuario: ");
        
      
       
      
        c = JOptionPane.showInputDialog("Ingrese su Contraseña: ");
        try {

            SQL = " SELECT * FROM usuario WHERE usuario= '"+ encriptaEnMD5(cod)+"' AND  contraseña='"+ encriptaEnMD5(c)+"'";

            Statement st = null;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            rs.next();
            idf.setText(rs.getString("id$usu"));
            jTextUsuario.setText(cod);
            jPasswordField1.setText(c);
             txtn.setText(rs.getString("nombre"));
             txta.setText(rs.getString("apellido"));
             r1=(rs.getString("rol"));
             ac1=(rs.getString("activo"));
            this.jButguardar.setEnabled(true);

        } catch (SQLException ex) {

        }
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBuCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuCancelarActionPerformed
        this.nAction =1;
        habilitar();
        limpiar();
    }//GEN-LAST:event_jBuCancelarActionPerformed

    private void jButguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButguardarActionPerformed
       
        String   usuario,contraseña,id;
        String SQL;
        id=idf.getText();
        usuario=jTextUsuario.getText();
        String n=txtn.getText(), a=txta.getText(),r="5",ac="0";
        contraseña=jPasswordField1.getText();
        if((usuario.isEmpty())||(contraseña.isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Ingrese su nombre de usuario y contraseña");
        }
        else{
            PreparedStatement psd;
            switch(nAction){
                

                case 1: 
                     try{
                          Statement st = (Statement) cn.createStatement();
                     
                     ResultSet rs = st.executeQuery("SELECT * FROM usuario  WHERE usuario ='"+encriptaEnMD5(usuario)+"' AND  contraseña='"+encriptaEnMD5(contraseña)+"'     " );
         rs.last();
          
            
        

         int encontrado=rs.getRow();
         
         if(encontrado==1)
             
         {  
              new Thread(new usuarior()).start();
         }
         else{
             
                    SQL="INSERT INTO usuario(usuario,contraseña,nombre,apellido,rol,activo)VALUES (?,?,?,?,?,?)";
               
                    psd = cn.prepareStatement(SQL);
                    psd.setString(1,encriptaEnMD5(usuario));
                    psd.setString(2,encriptaEnMD5(contraseña));
                     psd.setString(3,n );
                      psd.setString(4,a);
                       psd.setString(5,r);
                        psd.setString(6,ac);
                    int m= psd.executeUpdate();

                    if(m>0){

                        limpiar();
                        inhabilitar();
                       new Thread(new correcto1()).start();

                    }}}
                    catch(SQLException ex)  {

                       new Thread(new incorrecto()).start();

                    }
            
            
        
    
        
                    break;
                    case 2:
                        try {
                        Statement st = (Statement) cn.createStatement();
                     
                     ResultSet rs = st.executeQuery("SELECT * FROM usuario  WHERE usuario ='"+encriptaEnMD5(usuario)+"' AND  contraseña='"+encriptaEnMD5(contraseña)+"' AND  id$usu<>'"+id+"'     " );
         rs.last();
          
            
        

         int encontrado=rs.getRow();
         
         if(encontrado==1)
             
         {   
              new Thread(new usuarior()).start();
         }
         else{
                    SQL= "UPDATE usuario set usuario=?, contraseña=?, nombre=?,apellido=?,rol=?,activo=? WHERE id$usu = '"+id+"'  ";

                    
                        psd=cn.prepareStatement(SQL);
                        psd.setString(1,encriptaEnMD5(usuario));
                        psd.setString(2,encriptaEnMD5(contraseña));
                        psd.setString(3,n);
                        psd.setString(4,a);
                         psd.setString(5,r1);
                          psd.setString(6,ac1);
                        int s= psd.executeUpdate();
                        if (s>0) {

                            limpiar();
                            inhabilitar();
                           new Thread(new correcto1()).start();

                        }

                    }}
                    catch(SQLException ex)  {

                       new Thread(new incorrecto()).start();

                    }
                    break;
                }
            }
    }//GEN-LAST:event_jButguardarActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
    Acceso1 d=new Acceso1();
d.setVisible(true);

}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idf;
    private javax.swing.JButton jBuCancelar;
    private javax.swing.JButton jButguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel lbcontraseña;
    private javax.swing.JTextField txta;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
