/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * correcto.java
 *
 * Created on 25-jul-2016, 10:47:08
 */
package fenix2;

import Conexion_Base_de_Datos.conexionMySQL;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author GERALDO J
 */
public class correcto extends javax.swing.JFrame implements Runnable {
 private int x=0; int y=120,velocidad=30;
    Thread Hilo1,Hilo2;
    conexionMySQL mysql = new conexionMySQL();
          Connection cn = (Connection) mysql.Conectar();
       
    /** Creates new form correcto */
    public correcto() {
        this.setUndecorated(true);
        initComponents();
        i();
         this.setSize(x,y);
        nombre();
         setLocationRelativeTo(null);
    }
    void i(){
    Image icon;
    icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Iconos/ful3.png"));
   
            
            
    setIconImage(icon);
    setVisible(true);
  }
void nombre(){
    try
       {
            Statement st = (Statement) cn.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM usuario  WHERE activo ='"+1+"'  AND   activo <>'"+0+"'  " );
         rs.last();
          
            
        

         int encontrado=rs.getRow();
         
         if(encontrado==1)
             
         {  
             
           String   SQL = " SELECT * FROM usuario WHERE activo ='"+1+"' "; 
         
          Statement sv = null;
            sv = cn.createStatement();
            ResultSet rv = sv.executeQuery(SQL);
            rv.next(); 
           
         
        
         
          lbn.setText(rv.getString("nombre")); 
          lba.setText(rv.getString("apellido")); 
         
          
         
          
            
           
            
         }
         
         
         else
         {
            JOptionPane.showMessageDialog(null,"0","ERROR", JOptionPane.ERROR_MESSAGE);
      
         }

         rs.close();
         st.close();
       }
       catch (Exception e)
      {
      }
       
   
  
      
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbn = new javax.swing.JLabel();
        lba = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hola!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 47, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Seguir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 80, 70, 23);

        lbn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lbn);
        lbn.setBounds(40, 40, 100, 27);

        lba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lba);
        lba.setBounds(132, 40, 110, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
       {
            Statement st = (Statement) cn.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM usuario  WHERE activo ='"+1+"'  AND   activo <>'"+0+"'  " );
         rs.last();
          
            
        

         int encontrado=rs.getRow();
         
         if(encontrado==1)
             
         {  
             
           String   SQL = " SELECT * FROM usuario WHERE activo ='"+1+"' "; 
         
          Statement sv = null;
            sv = cn.createStatement();
            ResultSet rv = sv.executeQuery(SQL);
            rv.next(); 
           
         
        
         String id=(rv.getString("id$usu"));
          
        String   SQL2 = " SELECT * FROM prorolact WHERE Activo ='"+id+"' "; 
         
          Statement sd = null;
            sd = cn.createStatement();
            ResultSet rc = sd.executeQuery(SQL2);
            rc.next(); 
         
             String id2=(rc.getString("id$3"));
             
            String SQL1= "UPDATE prorolact set Activo=? WHERE id$3=?";
              PreparedStatement psd = cn.prepareStatement(SQL1);
            psd.setString(1, "1");
             psd.setString(2, id2);
            psd.executeUpdate(); 
            cerrar();
         new Thread(new Principal()).start();
             String SQL3= "UPDATE prorolact set Activo=? WHERE id$3=?";
              PreparedStatement psd2 = cn.prepareStatement(SQL3);
            psd2.setString(1, id);
             psd2.setString(2, id2);
            psd2.executeUpdate();
            
           
          
            
         
          
            
           
            
         }
         
         
         else
         {
            JOptionPane.showMessageDialog(null,"0","ERROR", JOptionPane.ERROR_MESSAGE);
      
         }

         rs.close();
         st.close();
       }
       catch (Exception e)
      {
      }
       
   
  
      
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(correcto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                  new Thread(new correcto()).start();
            }
        });
    }
     void cerrar(){
        try{
       this.setVisible(true);
       for(int i=0;i<7;i++){
           Hilo1.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           x=x-40;
          if(x==100000){
           for(int j=0;j<6;j++){
           Hilo2.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           y=y-100;   
          } 
       }
       }
        }catch(InterruptedException e){
            
        } 
        this.dispose();
    }
    public void run(){
        try{
       this.setVisible(true);
       for(int i=0;i<7;i++){
           Hilo1.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           x=x+40;
          if(x==100000 ){
           for(int j=0;j<6;j++){
           Hilo2.sleep(velocidad);
           this.setSize(x,y);
           this.setLocationRelativeTo(null);
           y=y+100;   
          } 
       }
       }
        }catch(InterruptedException e){
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lba;
    private javax.swing.JLabel lbn;
    // End of variables declaration//GEN-END:variables
}
